openapi: 3.0.4
info:
  title: Characters API
  version: 1.0.0
  description: Plantilla  de Open Api 3.0.4 que proporciona una colecci칩n estructurada de cartas del universo Clash Royale, cada una representada como un objeto con atributos definidos. El objetivo principal de la API es permitir el acceso, consulta y manipulaci칩n de cartas utilizadas en el juego, 칰tiles para prop칩sitos como visualizaci칩n, an치lisis, edici칩n o implementaci칩n en un sistema de gesti칩n.

   Cada carta contiene propiedades clave como su nombre, calidad, clase, salud, ataque, fecha de creaci칩n y el ID la cual se agrega automaticamente. La informaci칩n est치 disponible en formato JSON, lo que la hace f치cilmente integrable con aplicaciones web, m칩viles o backend.

servers:
  - url: http://localhost:3000

paths:
  /characters:
    get:
      summary: Obtener una lista de personajes
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: N칰mero de p치gina
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: L칤mite de personajes por p치gina
      responses:
        '200':
          description: Lista de personajes
          content:
            application/json:
              schema:
                type: object
                properties:
                  PaginaActual:
                    type: integer
                    example: 1
                  NumTotalPaginas:
                    type: integer
                    example: 32
                  PersonajesPorPagina:
                    type: integer
                    example: 1
                  TotalPersonajes:
                    type: integer
                    example: 32
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 2
                        nombre:
                          type: string
                          example: Mago El칠ctrico
                        calidad:
                          type: string
                          example: 칄pica
                        clase:
                          type: string
                          example: Apoyo
                        salud:
                          type: integer
                          example: 944
                        ataque:
                          type: integer
                          example: 159
                        fechaCreacion:
                          type: string
                          format: date-time
                          example: "2025-06-24T00:00:00.000Z"

 
    post:
      summary: Crear un nuevo personaje
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nombre
                - calidad
                - clase
                - salud
                - ataque
              properties:
                nombre:
                  type: string
                  example: Perro Gelido
                calidad:
                  type: string
                  example: Epico
                clase:
                  type: string
                  example: Tanque
                salud:
                  type: integer
                  example: 5000
                ataque:
                  type: integer
                  example: 200
      responses:
        '200':
          description: Personaje creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 35
                  nombre:
                    type: string
                    example: Perro Gel
                  calidad:
                    type: string
                    example: Epico
                  clase:
                    type: string
                    example: Tanque
                  salud:
                    type: integer
                    example: 5000
                  ataque:
                    type: integer
                    example: 200
                  createdAt:
                    type: string
                    format: date-time
                    example: "2025-07-05T01:39:37.063Z"
        '400':
          description: Error de parametros
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    enum:
                      - Nombre es requerido
                      - Calidad es requerida
                      - Clase es requerida
                      - Salud debe ser un n칰mero
                      - Ataque debe ser un n칰mero
                  status: 
                    type: integer
                    example: 404
        '404':
          description: Character ya creado
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 404
                  message:
                    type: string 
                    example: "Alredy exist Character in database"

  /characters/{id}:
    delete:
      summary: Eliminar un personaje por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del personaje a eliminar
      responses:
        '200':
          description: Personaje eliminado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ok
        '404':
          description: Personaje no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Not delete character
                  status: 
                    type: integer
                    example: 404

  /api/ClashRoyale/Media:
    post:
      summary: Obtener publicaciones oficiales de Clash Royale
      description: >
        Este endpoint permite obtener publicaciones del perfil oficial de Clash Royale desde la API de Twitter. 
        Requiere autenticaci칩n Bearer (el mismo token del body) y env칤o obligatorio de `token` y `query`.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - query
              properties:
                token:
                  type: string
                  example: AAAAAAAAAAAAAAAAAAAAADXo2AEAAAAAb1irf1fBFB4AyI6rf3ORVJU3jWI%3DlVoj1Q4z6YDIycoAXgxRg8CmnPRdEs7FqJ9rDb2RnB2NzvzxdA
                query:
                  type: string
                  example: from:ClashRoyale
      responses:
        '200':
          description: Publicaciones recuperadas exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "1943777316498551191"
                    text:
                      type: string
                      example: "One Barrel not enough? How 'bout two? 游\n\nSkeleton Barrel Evolution Draft Challenge awaits https://t.co/tWk821lYTf"
                    author:
                      type: string
                      example: "ClashRoyale"

        '400':
          description: Faltan par치metros obligatorios en el body
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad request, token and query are required

        '429':
          description: L칤mite de peticiones excedido (rate limit de Twitter)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Error from Twitter API
                  details:
                    type: string
                    example: '{"title":"Too Many Requests","detail":"Too Many Requests","type":"about:blank","status":429}'
